# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AckWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AckWindow(object):
    def setupUi(self, AckWindow):
        AckWindow.setObjectName("AckWindow")
        AckWindow.resize(300, 150)
        self.background_frame = QtWidgets.QFrame(AckWindow)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 300, 150))
        self.background_frame.setStyleSheet("QFrame{\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}")
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.message_label = QtWidgets.QLabel(self.background_frame)
        self.message_label.setGeometry(QtCore.QRect(15, 0, 270, 80))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("background: none; border: none;")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setWordWrap(True)
        self.message_label.setObjectName("message_label")
        self.ok_button = QtWidgets.QPushButton(self.background_frame)
        self.ok_button.setGeometry(QtCore.QRect(50, 116, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet("background: none;")
        self.ok_button.setText("")
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(self.background_frame)
        self.cancel_button.setGeometry(QtCore.QRect(165, 116, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background: none;")
        self.cancel_button.setText("")
        self.cancel_button.setObjectName("cancel_button")
        self.label = QtWidgets.QLabel(self.background_frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 150))
        self.label.setStyleSheet("border: none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/background_ack.png"))
        self.label.setObjectName("label")
        self.label.raise_()
        self.message_label.raise_()
        self.ok_button.raise_()
        self.cancel_button.raise_()

        self.retranslateUi(AckWindow)
        QtCore.QMetaObject.connectSlotsByName(AckWindow)

    def retranslateUi(self, AckWindow):
        _translate = QtCore.QCoreApplication.translate
        AckWindow.setWindowTitle(_translate("AckWindow", "Dialog"))
        self.message_label.setText(_translate("AckWindow", "TextLabel"))
