# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AuthorizationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindow(object):
    def setupUi(self, AuthorizationWindow):
        AuthorizationWindow.setObjectName("AuthorizationWindow")
        AuthorizationWindow.setWindowModality(QtCore.Qt.NonModal)
        AuthorizationWindow.setEnabled(True)
        AuthorizationWindow.resize(300, 200)
        AuthorizationWindow.setMouseTracking(True)
        self.main_frame = QtWidgets.QFrame(AuthorizationWindow)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 300, 300))
        self.main_frame.setMouseTracking(True)
        self.main_frame.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.header_label = QtWidgets.QLabel(self.main_frame)
        self.header_label.setGeometry(QtCore.QRect(0, 0, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setMouseTracking(True)
        self.header_label.setStyleSheet("color: #333")
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.password_line_edit = QtWidgets.QLineEdit(self.main_frame)
        self.password_line_edit.setGeometry(QtCore.QRect(15, 155, 270, 30))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(9)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setMouseTracking(True)
        self.password_line_edit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.password_line_edit.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: #f5f5f5;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid #999;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 1px solid #444;\n"
"}")
        self.password_line_edit.setMaxLength(20)
        self.password_line_edit.setFrame(True)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_line_edit.setClearButtonEnabled(False)
        self.password_line_edit.setObjectName("password_line_edit")
        self.auth_cat_label = QtWidgets.QLabel(self.main_frame)
        self.auth_cat_label.setGeometry(QtCore.QRect(203, 127, 70, 33))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        self.auth_cat_label.setFont(font)
        self.auth_cat_label.setMouseTracking(True)
        self.auth_cat_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.auth_cat_label.setText("")
        self.auth_cat_label.setPixmap(QtGui.QPixmap("img/kitty.png"))
        self.auth_cat_label.setObjectName("auth_cat_label")
        self.background_label = QtWidgets.QLabel(self.main_frame)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.background_label.setMouseTracking(True)
        self.background_label.setStyleSheet("border-radius: 15px;")
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("img/background_auth.png"))
        self.background_label.setScaledContents(True)
        self.background_label.setAlignment(QtCore.Qt.AlignCenter)
        self.background_label.setObjectName("background_label")
        self.info_label = QtWidgets.QLabel(self.main_frame)
        self.info_label.setGeometry(QtCore.QRect(0, 86, 291, 60))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.info_label.setFont(font)
        self.info_label.setMouseTracking(True)
        self.info_label.setStyleSheet("color: #191919")
        self.info_label.setScaledContents(False)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.left_eye_label = QtWidgets.QLabel(self.main_frame)
        self.left_eye_label.setGeometry(QtCore.QRect(225, 141, 10, 10))
        self.left_eye_label.setMouseTracking(True)
        self.left_eye_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.left_eye_label.setText("")
        self.left_eye_label.setPixmap(QtGui.QPixmap("img/cats eye.png"))
        self.left_eye_label.setObjectName("left_eye_label")
        self.right_eye_label = QtWidgets.QLabel(self.main_frame)
        self.right_eye_label.setGeometry(QtCore.QRect(242, 141, 10, 10))
        self.right_eye_label.setMouseTracking(True)
        self.right_eye_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.right_eye_label.setText("")
        self.right_eye_label.setPixmap(QtGui.QPixmap("img/cats eye.png"))
        self.right_eye_label.setObjectName("right_eye_label")
        self.close_label = QtWidgets.QLabel(self.main_frame)
        self.close_label.setGeometry(QtCore.QRect(273, 5, 15, 15))
        self.close_label.setMouseTracking(True)
        self.close_label.setText("")
        self.close_label.setPixmap(QtGui.QPixmap("img/close.png"))
        self.close_label.setScaledContents(True)
        self.close_label.setAlignment(QtCore.Qt.AlignCenter)
        self.close_label.setObjectName("close_label")
        self.background_label.raise_()
        self.info_label.raise_()
        self.header_label.raise_()
        self.password_line_edit.raise_()
        self.auth_cat_label.raise_()
        self.right_eye_label.raise_()
        self.left_eye_label.raise_()
        self.close_label.raise_()

        self.retranslateUi(AuthorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindow)

    def retranslateUi(self, AuthorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindow.setWindowTitle(_translate("AuthorizationWindow", "Dialog"))
        self.header_label.setText(_translate("AuthorizationWindow", "Авторизация"))
        self.password_line_edit.setPlaceholderText(_translate("AuthorizationWindow", "Введите пароль"))
        self.auth_cat_label.setToolTip(_translate("AuthorizationWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#20b2aa;\">Мяу~</span></p></body></html>"))
        self.info_label.setText(_translate("AuthorizationWindow", "Для этого действия необходимо подтвердить личность"))
        self.left_eye_label.setToolTip(_translate("AuthorizationWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#20b2aa;\">Мяу~</span></p></body></html>"))
        self.right_eye_label.setToolTip(_translate("AuthorizationWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#20b2aa;\">Мяу~</span></p></body></html>"))
