# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AuthWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.setEnabled(True)
        AuthWindow.resize(400, 300)
        AuthWindow.setMouseTracking(True)
        self.main_frame = QtWidgets.QFrame(AuthWindow)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.main_frame.setMouseTracking(True)
        self.main_frame.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.header_label = QtWidgets.QLabel(self.main_frame)
        self.header_label.setGeometry(QtCore.QRect(0, 0, 400, 50))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setMouseTracking(True)
        self.header_label.setStyleSheet("color: #333")
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.password_line_edit = QtWidgets.QLineEdit(self.main_frame)
        self.password_line_edit.setGeometry(QtCore.QRect(20, 255, 360, 30))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(9)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setMouseTracking(True)
        self.password_line_edit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.password_line_edit.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background: #f5f5f5;\n"
"    border: 0px;\n"
"    border-bottom: 1px solid #999;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-bottom: 1px solid #444;\n"
"}")
        self.password_line_edit.setMaxLength(20)
        self.password_line_edit.setFrame(True)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_line_edit.setClearButtonEnabled(False)
        self.password_line_edit.setObjectName("password_line_edit")
        self.auth_cat_label = QtWidgets.QLabel(self.main_frame)
        self.auth_cat_label.setGeometry(QtCore.QRect(303, 227, 70, 33))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        self.auth_cat_label.setFont(font)
        self.auth_cat_label.setMouseTracking(True)
        self.auth_cat_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.auth_cat_label.setText("")
        self.auth_cat_label.setPixmap(QtGui.QPixmap("img/kitty.png"))
        self.auth_cat_label.setObjectName("auth_cat_label")
        self.avatar_label = QtWidgets.QLabel(self.main_frame)
        self.avatar_label.setGeometry(QtCore.QRect(142, 50, 118, 118))
        self.avatar_label.setMouseTracking(True)
        self.avatar_label.setStyleSheet("QLabel {\n"
"    border-radius: 58px;\n"
"}")
        self.avatar_label.setText("")
        self.avatar_label.setPixmap(QtGui.QPixmap("img/avatars/su.png"))
        self.avatar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.avatar_label.setObjectName("avatar_label")
        self.background_label = QtWidgets.QLabel(self.main_frame)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.background_label.setMouseTracking(True)
        self.background_label.setStyleSheet("border-radius: 15px;")
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("img/background_auth.png"))
        self.background_label.setAlignment(QtCore.Qt.AlignCenter)
        self.background_label.setObjectName("background_label")
        self.info_label = QtWidgets.QLabel(self.main_frame)
        self.info_label.setGeometry(QtCore.QRect(0, 185, 400, 60))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.info_label.setFont(font)
        self.info_label.setMouseTracking(True)
        self.info_label.setStyleSheet("color: #191919")
        self.info_label.setScaledContents(False)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.left_eye_label = QtWidgets.QLabel(self.main_frame)
        self.left_eye_label.setGeometry(QtCore.QRect(325, 241, 10, 10))
        self.left_eye_label.setMouseTracking(True)
        self.left_eye_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.left_eye_label.setText("")
        self.left_eye_label.setPixmap(QtGui.QPixmap("img/cats eye.png"))
        self.left_eye_label.setObjectName("left_eye_label")
        self.right_eye_label = QtWidgets.QLabel(self.main_frame)
        self.right_eye_label.setGeometry(QtCore.QRect(342, 241, 10, 10))
        self.right_eye_label.setMouseTracking(True)
        self.right_eye_label.setStyleSheet("QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    font-family: \"Comfortaa\";\n"
"}")
        self.right_eye_label.setText("")
        self.right_eye_label.setPixmap(QtGui.QPixmap("img/cats eye.png"))
        self.right_eye_label.setObjectName("right_eye_label")
        self.close_label = QtWidgets.QLabel(self.main_frame)
        self.close_label.setGeometry(QtCore.QRect(373, 5, 21, 21))
        self.close_label.setMouseTracking(True)
        self.close_label.setText("")
        self.close_label.setPixmap(QtGui.QPixmap("img/close.png"))
        self.close_label.setAlignment(QtCore.Qt.AlignCenter)
        self.close_label.setObjectName("close_label")
        self.minimize_label = QtWidgets.QLabel(self.main_frame)
        self.minimize_label.setGeometry(QtCore.QRect(150, 8, 100, 5))
        self.minimize_label.setMouseTracking(True)
        self.minimize_label.setStyleSheet("QLabel {\n"
"background: #ccc;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"background: #aaa;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"QToolTip {\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 5px;\n"
"}")
        self.minimize_label.setText("")
        self.minimize_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minimize_label.setObjectName("minimize_label")
        self.background_label.raise_()
        self.info_label.raise_()
        self.header_label.raise_()
        self.avatar_label.raise_()
        self.password_line_edit.raise_()
        self.auth_cat_label.raise_()
        self.right_eye_label.raise_()
        self.left_eye_label.raise_()
        self.close_label.raise_()
        self.minimize_label.raise_()

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Dialog"))
        self.header_label.setText(_translate("AuthWindow", "Аутентификация"))
        self.password_line_edit.setPlaceholderText(_translate("AuthWindow", "Введите пароль"))
        self.auth_cat_label.setToolTip(_translate("AuthWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#31a15a;\">Мяу~</span></p></body></html>"))
        self.info_label.setText(_translate("AuthWindow", "Для доступа к приложению необходимо подтвердить личность (пароль 12345)"))
        self.left_eye_label.setToolTip(_translate("AuthWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#31a15a;\">Мяу~</span></p></body></html>"))
        self.right_eye_label.setToolTip(_translate("AuthWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#31a15a;\">Мяу~</span></p></body></html>"))
        self.minimize_label.setToolTip(_translate("AuthWindow", "Свернуть окно"))
