# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePasswdWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePassword(object):
    def setupUi(self, ChangePassword):
        ChangePassword.setObjectName("ChangePassword")
        ChangePassword.resize(250, 150)
        self.header_label = QtWidgets.QLabel(ChangePassword)
        self.header_label.setGeometry(QtCore.QRect(0, 0, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setStyleSheet("border-radius: 10px;")
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.new_password_line_edit = QtWidgets.QLineEdit(ChangePassword)
        self.new_password_line_edit.setGeometry(QtCore.QRect(30, 50, 190, 20))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_password_line_edit.setFont(font)
        self.new_password_line_edit.setStyleSheet("QLineEdit {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 1px solid #555;\n"
"    padding: 2px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QLineEdit:hover {\n"
"    border-bottom: 1px solid #333;\n"
"}")
        self.new_password_line_edit.setMaxLength(20)
        self.new_password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.new_password_line_edit.setObjectName("new_password_line_edit")
        self.new_password_confirmation_line_edit = QtWidgets.QLineEdit(ChangePassword)
        self.new_password_confirmation_line_edit.setGeometry(QtCore.QRect(30, 80, 190, 20))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.new_password_confirmation_line_edit.setFont(font)
        self.new_password_confirmation_line_edit.setStyleSheet("QLineEdit {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 1px solid #555;\n"
"    padding: 2px;\n"
"    color: black;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QLineEdit:hover {\n"
"    border-bottom: 1px solid #333;\n"
"}")
        self.new_password_confirmation_line_edit.setMaxLength(20)
        self.new_password_confirmation_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password_confirmation_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.new_password_confirmation_line_edit.setObjectName("new_password_confirmation_line_edit")
        self.background_label = QtWidgets.QLabel(ChangePassword)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 250, 150))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.background_label.setFont(font)
        self.background_label.setStyleSheet("border-radius: 15px;")
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("img/background_change_password.png"))
        self.background_label.setAlignment(QtCore.Qt.AlignCenter)
        self.background_label.setObjectName("background_label")
        self.change_button = QtWidgets.QPushButton(ChangePassword)
        self.change_button.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.change_button.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 1px solid black; \n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #333;\n"
"    border: 1px solid #333\n"
"}")
        self.change_button.setObjectName("change_button")
        self.cancel_button = QtWidgets.QPushButton(ChangePassword)
        self.cancel_button.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.cancel_button.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: 1px solid black; \n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #333;\n"
"    border: 1px solid #333\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.message_label = QtWidgets.QLabel(ChangePassword)
        self.message_label.setGeometry(QtCore.QRect(0, 24, 250, 30))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.message_label.setFont(font)
        self.message_label.setStyleSheet("border-radius: 10px;\n"
"color: #d11;")
        self.message_label.setText("")
        self.message_label.setAlignment(QtCore.Qt.AlignCenter)
        self.message_label.setObjectName("message_label")
        self.background_label.raise_()
        self.header_label.raise_()
        self.new_password_line_edit.raise_()
        self.new_password_confirmation_line_edit.raise_()
        self.change_button.raise_()
        self.cancel_button.raise_()
        self.message_label.raise_()

        self.retranslateUi(ChangePassword)
        QtCore.QMetaObject.connectSlotsByName(ChangePassword)

    def retranslateUi(self, ChangePassword):
        _translate = QtCore.QCoreApplication.translate
        ChangePassword.setWindowTitle(_translate("ChangePassword", "Dialog"))
        self.header_label.setText(_translate("ChangePassword", "Установите новый пароль"))
        self.new_password_line_edit.setPlaceholderText(_translate("ChangePassword", "Новый пароль"))
        self.new_password_confirmation_line_edit.setPlaceholderText(_translate("ChangePassword", "Повторите новый пароль"))
        self.change_button.setText(_translate("ChangePassword", "Сменить"))
        self.cancel_button.setText(_translate("ChangePassword", "Отмена"))
