# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TemplatesWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemplatesWindow(object):
    def setupUi(self, TemplatesWindow):
        TemplatesWindow.setObjectName("TemplatesWindow")
        TemplatesWindow.resize(600, 400)
        self.background_frame = QtWidgets.QFrame(TemplatesWindow)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.background_frame.setStyleSheet("QFrame{\n"
"    background: white;\n"
"    border-radius: 10px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"background: rgba(0,0,0,10);\n"
"width: 8px;\n"
"margin: 1px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background-color: #777;\n"
"min-height: 20px;\n"
"border-radius: 2px;\n"
"margin: 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"background-color: #555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    border-radius: 4px;\n"
"    background: rgba(0,0,0,10);\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #777;\n"
"    min-width: 20px;\n"
"    border-radius: 2px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.ok_button = QtWidgets.QPushButton(self.background_frame)
        self.ok_button.setGeometry(QtCore.QRect(30, 360, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background: none;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-color: #222;\n"
"color: #222\n"
"}")
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(self.background_frame)
        self.cancel_button.setGeometry(QtCore.QRect(480, 360, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background: none;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-color: #222;\n"
"color: #222\n"
"}")
        self.cancel_button.setObjectName("cancel_button")
        self.background = QtWidgets.QLabel(self.background_frame)
        self.background.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background_templates.png"))
        self.background.setObjectName("background")
        self.scroll_area_templates = QtWidgets.QScrollArea(self.background_frame)
        self.scroll_area_templates.setGeometry(QtCore.QRect(10, 10, 581, 341))
        self.scroll_area_templates.setStyleSheet("QScrollArea {\n"
"background: rgba(255,255,255,0);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"background: rgba(0,0,0,10);\n"
"width: 8px;\n"
"margin: 1px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background-color: #777;\n"
"min-height: 20px;\n"
"border-radius: 2px;\n"
"margin: 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"background-color: #555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    border-radius: 4px;\n"
"    background: rgba(0,0,0,10);\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #777;\n"
"    min-width: 20px;\n"
"    border-radius: 2px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.scroll_area_templates.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_templates.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_templates.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scroll_area_templates.setWidgetResizable(True)
        self.scroll_area_templates.setObjectName("scroll_area_templates")
        self.templates_widget_contents = QtWidgets.QWidget()
        self.templates_widget_contents.setEnabled(True)
        self.templates_widget_contents.setGeometry(QtCore.QRect(0, 0, 579, 339))
        self.templates_widget_contents.setStyleSheet("QWidget {\n"
"background: rgba(255,255,255,0);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"background: rgba(0,0,0,10);\n"
"width: 8px;\n"
"margin: 1px;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"background-color: #777;\n"
"min-height: 20px;\n"
"border-radius: 2px;\n"
"margin: 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"background-color: #555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    border-radius: 4px;\n"
"    background: rgba(0,0,0,10);\n"
"    height: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #777;\n"
"    min-width: 20px;\n"
"    border-radius: 2px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}")
        self.templates_widget_contents.setObjectName("templates_widget_contents")
        self.scroll_area_templates.setWidget(self.templates_widget_contents)
        self.create_button = QtWidgets.QPushButton(self.background_frame)
        self.create_button.setGeometry(QtCore.QRect(180, 360, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.create_button.setFont(font)
        self.create_button.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background: none;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-color: #222;\n"
"color: #222\n"
"}")
        self.create_button.setObjectName("create_button")
        self.delete_button = QtWidgets.QPushButton(self.background_frame)
        self.delete_button.setGeometry(QtCore.QRect(330, 360, 90, 26))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background: none;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border-color: #222;\n"
"color: #222\n"
"}")
        self.delete_button.setObjectName("delete_button")
        self.background.raise_()
        self.cancel_button.raise_()
        self.ok_button.raise_()
        self.scroll_area_templates.raise_()
        self.create_button.raise_()
        self.delete_button.raise_()

        self.retranslateUi(TemplatesWindow)
        QtCore.QMetaObject.connectSlotsByName(TemplatesWindow)

    def retranslateUi(self, TemplatesWindow):
        _translate = QtCore.QCoreApplication.translate
        TemplatesWindow.setWindowTitle(_translate("TemplatesWindow", "Dialog"))
        self.ok_button.setText(_translate("TemplatesWindow", "Ок"))
        self.cancel_button.setText(_translate("TemplatesWindow", "Отмена"))
        self.create_button.setText(_translate("TemplatesWindow", "Создать"))
        self.delete_button.setText(_translate("TemplatesWindow", "Удалить"))
